
var question=0;

function getCookie(cname) {
  let name = cname + "=";
  let decodedCookie = decodeURIComponent(document.cookie);
  let ca = decodedCookie.split(';');
  for(let i = 0; i <ca.length; i++) {
    let c = ca[i];
    while (c.charAt(0) == ' ') {
      c = c.substring(1);
    }
    if (c.indexOf(name) == 0) {
      return c.substring(name.length, c.length);
    }
  }
  return "";
}

function setCookie(cname, cvalue) {
  const d = new Date();
  d.setTime(d.getTime() + (365 * 24 * 60 * 60 * 1000));
  let expires = "expires="+d.toUTCString();
  document.cookie = cname + "=" + cvalue + ";" + expires + ";path=/";
}

function setupCookies(){
  question = getCookie("question");
  if (typeof question === 'undefined' || question == ""){
    setCookie("question", 0);
    question=0;
    if (typeof getCookie("question") === 'undefined' || getCookie("question") == ""){
      alert("Oops, cookies are not working properly on your browser! Your results will not be stored when you leave this page.");
    }else{
      alert("Cookies are set up properly, you are at question "+question);
    }
  }
}

function nextQuestion(){
  var result = possibleQuestions[question] + "|" + document.getElementById("answer").value.trim() + "|";
  setCookie("results",getCookie("results").concat(result.trim()));
  setCookie("question",(question+1));
  question++;
  if(possibleQuestions.length>question){         document.getElementById("question").innerHTML=possibleQuestions[question];
  }else{
    setCookie("question",0);
    question=0;
    document.getElementById("question").innerHTML=possibleQuestions[0];
  }
}

function skipQuestion(){
  
}

function displayResults(){
  rawResults=getCookie("results");
  resultsList=rawResults.split("|");
  console.log(resultsList);
  results="";
  for (var i = 0; i < resultsList.length-1; i=i+2){
    segment = resultsList[i]+"<br>"+resultsList[i+1]+"<br><br>";
    console.log("Segment: "+segment);
    results=results+segment;
    console.log("Results: "+results);
  }
  
  document.getElementById("results").innerHTML=results;
  //document.getElementById("results").value=getCookie("results");
}

function checkEnter() {
  if(event.keyCode == 13) {
    nextQuestion();
    document.getElementById("answer").value="\n\n";
  }
}

function closePopup() {
  document.getElementById("popup").style.display = "none";
  document.getElementById("notpopup").style.display = "table";
  document.getElementById("answer").value="\n\n";
  document.getElementById("answer").focus();
  document.getElementById("question").innerHTML=possibleQuestions[question]+getCookie("question");
}

possibleQuestions = [
"How did you meet a special person in your life?", 
"Who is the person you admire most?", 
"What is the best place in your area?", 
"What is a place where you would like to live your whole life?", 
"What is a work of art you admire?", 
"What is the job of your dream?", 
"What is your greatest disappointment?", 
"What books made a great impression on you?", 
"What annoys you?", 
"What are your family traditions?", 
"Are you addicted to technology?", 
"What modern songs inspire you?", 
"Could you live without money?", 
"Do you like commercials?", 
"What is your best method of studying?", 
"What is the most unfortunate event that has ever happened to you?", 
"What happened during your first day at school?", 
"What is your first childhood memory?", 
"What is your most memorable family event?", 
"Have you experienced failure?", 
"What games did you play when you were a child?", 
"What is the biggest challenge you have overcome?", 
"Do you remember your first birthday party?", 
"How do you learn something new?", 
"Have you ever encountered a wild animal?", 
"What was the first time you were home alone?", 
"How did you cook a meal for the first time?", 
"How have you helped someone?", 
"How have you overcome fear?", 
"What things make you feel happy?", 
"How do you celebrate Christmas or any other holiday?", 
"Did you bring a stray animal home?", 
"How did you learn to drive?", 
"How were you impacted by meeting a famous person?", 
"How did you learn something from enemies?", 
"What is an accident you've witnessed?", 
"How have you gotten hurt?", 
"What was your most disastrous trip or vacations?", 
"What are some fantastic concerts you've attended?", 
"What are your most terrifying nightmares about?", 
"What are your favorite dreams of?", 
"What is your reaction when provoked?", 
"How are you a leader?", 
"What was a friendship breakup you've experienced?", 
"What could you live without?", 
"Why are you concerned (or not) about environmental issues?", 
"How much money do you need for happiness?", 
"What does your ethnic identity mean to you?", 
"How do you see gendered roles in your family?", 
"What is your attitude to feminism?", 
"What does it mean to be a human?", 
"What is life about?", 
"What does it mean to be successful?", 
"What are the most precious moments of your life?", 
"What is more critical: wealth or happiness?", 
"Would you get a tattoo?", 
"Is it important to care about appearance?", 
"What is the significance of healthy lifestyle choices?", 
"What is your favorite holiday destinations?", 
"Have you been in love with someone?", 
"What is your life’s goal?", 
"How does freedom matter in your life?", 
"How do you leave the comfort zone?", 
"What are the things you appreciate in life?", 
"What things do you hate?", 
"How did you get your first job?", 
"What are some intellectual challenges you would like to solve?", 
"What did you learn from failures?", 
"What outdoor activities do you like most?", 
"What are your commitments?", 
"What motivates you?", 
"What was your bravest moment?", 
"How did you meet your best friend?", 
"What makes people special to you?", 
"How did you overcome a fear?", 
"Why you will succeed?", 
"Why did you make a difficult choice?", 
"What is your special place?", 
"What is a place you try to avoid?", 
"When did a friend let you down?", 
"What was an event that changed your life?", 
"What was a special encounter with an animal?", 
"When was a time when you felt out of place?", 
"What was an odd experience that didn't make sense at the time?",
"What were words of wisdom that hit home and changed your way of thinking?", 
"Who is a person that you do not like?", 
"When was a time when you disappointed someone?", 
"What is your fondest memory?", 
"When was a time that you saw your parent cry?", 
"What was the moment when you knew you were grown up?", 
"What is your earliest memory of holiday celebrations in your home?", 
"When was a time when you should have made a better choice?", 
"When was a time when you dodged a dangerous situation?", 
"Who is a person you will think about at the end of your life?", 
"What is your favorite time period?",  
"What plot twists have you seen in your life?", 
"What you would do with power?", 
"What superpower you would choose?", 
"If you could switch lives with someone, who?", 
"How does money matter in your life?", 
"What was your biggest loss?", 
"When was a time when you felt you did the wrong thing?", 
"When was a proud moment when you did the right thing?", 
"What is an experience that you've never shared with another person?", 
"Where do you go to hide?", 
"If you had a do-over, what would you change?", 
"What were some words that stung?", 
"What words prompted hope for you?", 
"When did a child teach you a lesson?", 
"What was your favorite time with family?", 
"If you could live in another country, what country?", 
"How do you want to die?", 
"If you could invent something, what would it be?", 
"How will the world a hundred years from now be different because of you?", 
"If you had lived a hundred years earlier, how do you think you would be different?", 
"What is an animal you'd like to be?", 
"What is one thing you'd change at your school?", 
"What type of teacher would you would be?", 
"If you could be a building, which one?", 
"What is a statue you'd like to see?", 
"If you could live anywhere, where?", 
"What is the greatest discovery you've made?", 
"If you could change one thing about yourself, what?", 
"What is something you can do that robots could never do?", 
"What is your most unfortunate day?", 
"What is your secret talent?",
"What is your secret love?",
"What is the most beautiful thing you've ever seen?", 
"What is the ugliest thing you've seen?", 
"How would you spend a million dollars?", 
"If you could start a charity, what would it be?", 
"What is the meaning of color?", 
"What is your favorite gift?", 
"What chore would you do away with?", 
"What is something you can't resist?", 
"Who is a visitor you'll never forget?", 
"Was was an unexplained event?", 
"What was your longest minute?", 
"Why do you (or don't you) lie?", 
"What do you fundamentally disagree with someone you love on?", 
"What is the hardest news you've had to deliver?", 
"What’s the toughest decision you made today?",  
"What’s the toughest decision you made this year?",  
"What’s the toughest decision you ever made?",  
"What have you forgotten?",  
"If you were guaranteed the answer to one question, what would it be?",  
"What’s it like being you right now?",  
"What makes you nostalgic?",  
"If you had two hours left on earth what would you do?",  
"What’s the most beautiful word in the world?",  
"Who makes you laugh more than anyone?",  
"What did your father teach you?",  
"What did your mother teach you?",  
"What’s the best gift you’ve ever given?",  
"What was the best gift you ever received?",  
"How many times a day do you look in the mirror?",  
"What do you bring most to a friendship?",  
"If 100 people in your age group were selected randomly, how many do you think they’d find leading a happier life than you?",  
"What is or was your best subject in school?",  
"What activity do you do that makes you feel most like yourself?",  
"What makes you feel supported?",  
"Whom do you secretly admire?",  
"What time of the day do you feel the most energetic and what do you usually do in those moments?",  
"What’s something you never leave home without?",  
"What’s a recurring dream you have?",  
"What makes you feel safe?",  
"What’s the best thing that ever happened to you?",  
"What do you want people to say about you once you’re gone?",  
"What’s the coolest thing about science?",  
"What’s the best money you ever spent?",  
"What’s a bad habit you have?",  
"What are you grateful for?",  
"Whom are you envious of?",  
"What’s an image you’ll never forget?",  
"If you had a clone, what would you have the clone do?",  
"What’s your idea of Heaven?",  
"What’s your idea of Hell?",  
"When did you know?",  
"What can you do better?",  
"When are you most yourself?",  
"What superpower would you most like to have?",  
"If you were granted three wishes, what would you do with the second wish?",  
"What is your actual superpower?",  
"If you won 100 million dollars, what would you buy first?",  
"What's the best sound in the world?",  
"What’s perfect about your life?",  
"What song do you sing only when you’re alone and what memory does it bring back?",  
"When was a moment you were so embarrassed you wanted to disappear?",
"How many times a day do you think about money?",  
"Who has been the biggest influence on you in your relationship to money?",  
"What's one thing you're certain of?",  
"What was one of your colossal failures?",
"What makes you cringe?",  
"What does your inner voice tell you?",  
"What crime have you considered committing?",  
"Which day would you gladly re-live?",  
"What are you awesome at?",  
"What do you want people you meet for the first time to think about you?",  
"When were you most afraid?",  
"What are you terrible at but love to do anyway?",  
"What weapon would you carry during the Zombie Apocalypse?",  
"Which of your five senses would you keep if you could only keep one?",  
"What’s something you love to make?",  
"What do you cook better than anyone?",  
"What do you wish you’d invented?",  
"Out of 100 random people, where would you rank yourself in terms of your intelligence?",  
"Where do you want to be right now?",  
"If you could be someone else for a day who would it be and why?",  
"What makes you feel powerful?",  
"What’s the meanest thing you’ve ever said?",  
"What’s the meanest thing someone has ever said to you?",  
"What three words would you have on your gravestone?",  
"What’s your first thought when you wake up?",  
"What’s one thing you wake up to in the middle of the night worrying about?",  
"If you could tell someone something anonymously, what would it be?",  
"Whom would you like to forgive and forget?",  
"If you could get rid of one of your responsibilities today, what would it be?",  
"What type of person angers you the most?",  
"What is your greatest strength?",  
"What is your worst weakness?",  
"How do you show your love for others?",  
"Why are you here in this room right now?",  
"When is a time you forgave someone or were forgiven for something?",  
"What’s the biggest mistake you ever made?",  
"What are you hiding?",  
"What’s your unanswerable question--the question you seem to always be asking yourself?",  
"What are you ashamed of?",  
"What is stopping you?",  
"What’s a secret you have?",  
"How do you secretly manipulate people to get your way?",  
"When was the last time you apologized?",  
"What is the biggest lie you tell yourself?",  
"What’s the moment you left childhood behind?",  
"What's missing from your life?",  
"Do you believe in a higher power?",  
"What are you ready to let go of?", 
"What are you not saying right now?",  
"What challenges have you overcome?", 
"What are your secret survival strategies?", 
"What do you do when you encounter obstacles to success?", 
"When have you failed?", 
"What did you learn from failure?", 
"When have you ever succeeded when you thought you might fail?", 
"What life lessons has adversity taught you?", 
"What work went into reaching your most difficult goals?", 
"How often do you leave your ‘comfort zone’?", 
"When was the last time you did something that scared or challenged you?", 
"What are you afraid of?", 
"What are your fears and phobias?", 
"What are your personal superstitions?", 
"Do you like being alone?", 
"How often do you cry?", 
"Do you ever feel overlooked and underappreciated?", 
"How have you handled being the ‘new kid’?", 
"How do you deal with haters?", 
"How do you react when provoked?", 
"What role does stress play in your life?", 
"Does stress affect your ability to make good decisions?", 
"How do you relieve stress?", 
"How do you find peace in your life?", 
"Does your life leave you enough time to relax?", 
"Do you set rules for yourself about how you use your time?", 
"Is ‘doing nothing’ a good use of your time?", 
"What did you once hate but now like?", 
"What kind of feedback helps you improve?", 
"Is trying too hard to be happy making you sad?", 
"Do adults who are ‘only trying to help’ sometimes make things worse?", 
"What is your personal credo?", 
"What motivates you?", 
"What makes you happy?", 
"What are you good at?", 
"When in your life have you been a leader?", 
"How well do you perform under pressure?", 
"How well do you take criticism?", 
"Are you hard or easy on yourself?", 
"How full is your glass?", 
"Do you have a hard time making decisions?", 
"How much self-control do you have?", 
"How good are you at waiting for what you really want?", 
"What role does procrastination play in your life?", 
"How good are you at time management?", 
"How productive and organized are you?", 
"Under what conditions do you do your best work?", 
"How do you express yourself creatively?", 
"Are you a good listener?", 
"How competitive are you?", 
"Do you perform better when you’re competing or when you’re collaborating?", 
"How emotionally intelligent are you?", 
"Do you take more risks when you are around your friends?", 
"Do you unknowingly submit to peer pressure?", 
"Do you think you’re brave?", 
"How much of a daredevil are you?", 
"Fallen for or perpetrated?", 
"How impulsive are you?", 
"Are you a novelty-seeker?", 
"How do you deal with boredom?", 
"What annoys you?", 
"Do you apologize too much?", 
"Do you have good manners?", 
"How materialistic are you?", 
"Are you a saver or a tosser?", 
"Are you a hoarder or a minimalist?", 
"Are you an introvert or an extrovert?", 
"Are you popular, quirky, or conformist?", 
"Are you a nerd or a geek?", 
"What would your personal mascot be?", 
"What assumptions do people make about you?", 
"How good are you at saying goodbye?", 
"Who is your role model?", 
"Who inspires you?", 
"Who are the people – famous or not – you admire most?", 
"Who are your heroes?", 
"What heroic acts have you performed or witnessed?", 
"What’s the best advice you’ve gotten?", 
"What are some ‘words of wisdom’ that guide your life?", 
"Who outside your family has made a difference in your life?", 
"If you had your own talk show, whom would you want to interview?", 
"To whom, or what, would you like to write a thank-you note?", 
"What leader would you invite to speak at your school?", 
"What six people, living or dead, would you invite to dinner?", 
"Who’s your ‘outsider role model’?", 
"Who is your family?", 
"How do you define ‘family’?", 
"What have you and your family accomplished together?", 
"What events have brought you closer to your family?", 
"What’s your role in your family?", 
"Have you ever changed a family member’s mind?", 
"How well do you get along with your siblings?", 
"What are your family stories of sacrifice?", 
"What possessions does your family treasure?", 
"What hobbies have been passed down in your family?", 
"What’s the story behind your name?", 
"What are your favorite names?", 
"How have you paid tribute to loved ones?", 
"What do you know about your family’s history?", 
"Did your parents have a life before they had kids?", 
"What family traditions do you want to carry on when you get older?", 
"How close are you to your parents?", 
"How are you and your parents alike and different?", 
"How much freedom have your parents given you?", 
"How permissive are your parents?", 
"Do you have helicopter parents?", 
"How do your parents teach you to behave?", 
"How do you make parenting difficult for your parents?", 
"How often do you fight with your parents?", 
"What advice would you give to your mom, dad, or guardian on how to be a better parent?", 
"Is your family stressed, tired, and rushed?", 
"Do your parents try too hard to be cool?", 
"Do you ever feel embarrassed by your parents?", 
"Do your parents support your learning?", 
"Do you talk about report cards with your parents?", 
"Do you want your parents to stop asking you ‘how was school?",
"How has your family helped or hindered your transition to a new school?", 
"Have your parents and teachers given you room to create?", 
"How much does your neighborhood define who you are?", 
"What’s special about your hometown?", 
"What marketing slogan would you use for your town or city?", 
"What would you name your neighborhood?", 
"Who are the ‘characters’ that make your town interesting?", 
"Who is the ‘mayor’ of your school or neighborhood?", 
"What would a tv show about your town spoof?", 
"What ‘urban legends’ are there about places in your area?", 
"Do you know your way around your city or town?", 
"How well do you know your neighbors?", 
"What is your favorite place?", 
"What’s your favorite neighborhood joint?", 
"What is your favorite street?", 
"Do you hang out in the park?", 
"How much time do you spend in nature?", 
"What small things have you seen and taken note of today?", 
"What buildings do you love?", 
"What buildings do you hate?", 
"What are the sounds that make up the background noise in your life?", 
"What sounds annoy you?", 
"What public behavior annoys you most?", 
"Have you ever interacted with the police?", 
"What local problems do you think your mayor should try to solve?", 
"What ideas do you have for enhancing your community?", 
"Where do you think you will live when you are an adult?", 
"Would you most want to live in a city, a suburb or the country?", 
"Is your bedroom a nightmare?", 
"What is your favorite place in your house?", 
"How important is keeping a clean house?", 
"Do you need to declutter your life?", 
"Do you plan on saving any of your belongings for the future?", 
"With your home in danger, what would you try to save?", 
"What would you grab in a fire?", 
"What would you put in your emergency ‘go-bag’?", 
"Who lived long ago where you live now?", 
"What would your dream home be like?", 
"What was your most precious childhood possession?", 
"What objects tell the story of your life?", 
"What do you collect?", 
"What were your favorite childhood shows and characters?", 
"Do you have childhood memories of being read aloud to?", 
"What were your favorite picture books when you were little?", 
"What things did you create when you were a child?", 
"What places do you remember fondly from childhood?", 
"What food or flavor do you remember tasting for the first time?", 
"What do you wish you could see, hear, read or experience for the first time all over again?", 
"Have you ever felt embarrassed by things you used to like?", 
"Do you wish you could return to moments from your past?", 
"Was there a toy you wanted as a child but never got?", 
"What’s the best gift you’ve ever given or received?", 
"What’s the most memorable thing you ever got in the mail?", 
"Have you ever lost (or found) something valuable?", 
"What nicknames have you ever gotten or given?", 
"What are your best sleepover memories?", 
"What old, worn-out thing can you just not part with?", 
"What is your most prized possession?", 
"What have you learned in your teens?", 
"What do you remember best about being twelve?", 
"What personal achievements make you proud?", 
"What are some recent moments of happiness in your life?", 
"What rites of passage have you participated in?", 
"What are you grateful for?", 
"What advice would you give younger kids about middle or high school?", 
"What have you learned from older people?", 
"What can older people learn from your generation?", 
"What do older generations misunderstand about yours?", 
"Do you recognize yourself in descriptions of ‘generation Z'?", 
"What ethical dilemmas have you faced?", 
"Have you ever had to make a sacrifice to help someone you care about?", 
"Have you ever donated your time, talents, possessions, or money to support anyone in need?", 
"When is the last time you did something nice for a stranger?", 
"Have you ever ‘paid it forward’?", 
"How trustworthy are you?", 
"How comfortable are you with lying?", 
"When do you lie?", 
"Have you ever lied to your parents or done something behind their backs?", 
"If you drink or use drugs, do your parents know?", 
"Have you ever taken something you weren’t supposed to?", 
"Do you ever eavesdrop?", 
"How much do you gossip?", 
"What is the role of religion or spirituality in your life?", 
"How important is your spiritual life?", 
"Do you believe that everything happens for a reason?", 
"How much control do you think you have over your fate?", 
"Can you be good without God?", 
"Are you less religious than your parents?", 
"Can you pass a basic religion test?", 
"What can you learn from other religions?", 
"Do parents have different hopes and standards for their sons than for their daughters?", 
"How do your parents share the responsibilities of parenting?", 
"Is there too much pressure on girls to have ‘perfect’ bodies?", 
"How much pressure do boys face to have the perfect body?", 
"How did you learn about sex?", 
"What experiences have you had with gender bias in school?", 
"What have been your experiences with catcalling or other kinds of street harassment?", 
"What does it mean to be ‘a real man’?", 
"Do you consider yourself a feminist?", 
"What is your racial and ethnic identity?", 
"Have you ever tried to hide your racial or ethnic identity?", 
"How often do you interact with people of another race or ethnicity?", 
"Do you ever talk about issues of race and class with your friends?", 
"Is your generation really ‘postracial’?", 
"What’s the racial makeup of your school?", 
"Does your school seem integrated?", 
"Have you experienced racism or other kinds of discrimination in school?", 
"What are your attitudes toward money?", 
"Are you a saver or a spender?", 
"What have your parents taught you about money?", 
"Do you expect your parents to give you money?", 
"How important a role has money, work, or social class played in your life?", 
"Do you see great disparities of wealth in your community?", 
"Can money buy you happiness?", 
"What are the best things in life and are they free?", 
"Are you distracted by technology?", 
"Are you distracted by your phone?", 
"Are you ‘addicted’ to texting?", 
"Do you always have your phone or tablet at your side?", 
"Do screens get in the way of the rest of your life?", 
"Do you experience FOMO when you unplug?", 
"Does your digital life have side effects?", 
"Do you spend too much time on smartphones playing ‘stupid games’?", 
"Do apps help you or just waste your time?", 
"What tech tools play the biggest role in your life?", 
"What new technologies or tech toys are you most excited about?", 
"To what piece of technology would you write a ‘love letter’?", 
"What are your favorite viral videos?", 
"What are your favorite internet spoofs?", 
"What would you teach the world in an online video?", 
"Do you ever seek advice on the internet?", 
"Would you share an embarrassing story online?", 
"How do you know if what you read online is true?", 
"What are your experiences with internet-based urban legends?", 
"How much do you trust online reviews?", 
"How careful are you online?", 
"What story does your personal data tell?", 
"Do you worry about the lack of anonymity in the digital age?", 
"Would you mind if your parents blogged about you?", 
"Do you wish you had more privacy online?", 
"Have you ever been scammed?", 
"Whom would you share your passwords with?", 
"Why do you share photos?", 
"How do you archive your life?", 
"Have you ever posted, emailed, or texted something you wish you could take back?", 
"Have you ever sent an odd message because of auto-correct?", 
"Would you want your photo or video to go viral?", 
"Do you worry colleges or employers might read your social media posts someday?", 
"What advice do you have for younger kids about navigating social media?", 
"What are you listening to?", 
"What songs are on your favorite playlist?", 
"What musicians or bands mean the most to you?", 
"What music inspires you?", 
"Who in your life introduces you to new music?", 
"How much is your taste in music based on what your friends like?", 
"What role does hip-hop play in your life?", 
"Which pop music stars fascinate you?", 
"Who is your favorite pop diva?", 
"What’s your karaoke song?", 
"Which artists would you like to see team up?", 
"How closely do you listen to lyrics?", 
"What are your earliest memories of music?", 
"What are the best things you’ve watched, read, heard, or played this year?", 
"What are your tv habits?", 
"Do your television viewing habits include ‘binge-watching’?", 
"What role does television play in your life and the life of your family?", 
"What television shows have mattered to you?", 
"How often do you watch a television show when it originally airs?", 
"Have you fallen into ‘friends’ or any other older television shows?", 
"What old television shows would you bring back?", 
"Why do we like reality shows so much?", 
"What ideas do you have for a reality show?", 
"What reality tv show would you want to be a guest star on?", 
"What are your favorite cartoons?", 
"What are your favorite commercials?", 
"How much are you influenced by advertising?", 
"What are your favorite movies ever?", 
"What were the best movies you saw in the past year?", 
"What movies do you watch, or reference, over and over?", 
"What movies, shows or books do you wish had sequels, spinoffs, or new episodes?", 
"Do you like horror movies?", 
"What is your favorite comedy?", 
"Who are your favorite movie stars?", 
"Would you pay extra for a three-dimensional movie?", 
"Where, and how, do you watch movies?", 
"What are the best live theatrical performances you’ve ever seen?", 
"Have you ever stumbled upon a cool public performance?", 
"What are your favorite video games?", 
"What have you learned playing video games?", 
"Do you play violent video games?", 
"When should you feel guilty for killing zombies?", 
"Who are your opponents in online gaming?", 
"Do you like watching other people play video games?", 
"How excited are you about the possibilities of virtual reality?", 
"Read any good books lately?", 
"What are the best books you’ve read this year?", 
"What are your favorite books and authors?", 
"What are your favorite young adult novels?", 
"Do you read for pleasure?", 
"What memorable poetry have you ever read or heard?", 
"What magazines do you read, and how do you read them?", 
"Do you enjoy reading tabloid gossip?", 
"When have you seen yourself and your life reflected in a book or other media?", 
"Has a book, movie, television show, song, or video game ever inspired you to do something new?", 
"Do you prefer your children’s book characters obedient or contrary?", 
"Do you read ebooks?", 
"Would you trade your paper books for digital versions?", 
"To what writer would you award a prize?", 
"Why do you write?", 
"Are you a good storyteller?", 
"What’s your favorite joke?", 
"Do you keep a diary or journal?", 
"Do you have a blog?", 
"Do you want to write a book?", 
"When do you write by hand?", 
"Do you write in cursive?", 
"Do you write in your books?", 
"What ‘mundane moments’ from your life might make great essay material?", 
"What is your most memorable writing assignment?", 
"Do you ever write about challenges you face in life?", 
"What’s the coolest thing you’ve ever seen in a museum?", 
"What are the most memorable works of visual art you have seen?", 
"What are your favorite works of art?", 
"How important is arts education?", 
"What has arts education done for you?", 
"What words do you hate?", 
"What words or phrases do you think are overused?", 
"How much slang do you use?", 
"What are your favorite words?", 
"What current slang words and expressions do you think will endure?", 
"Why do so many people say ‘like’ and ‘totally’ all the time?", 
"Do you say ‘kind of, sort of’ more than you realize?", 
"How much do you curse?", 
"How good are you at coming up with witty comebacks?", 
"When did you last have a great conversation?", 
"How often do you have ‘deep discussions’?", 
"Do you wish your conversations were less small talk and more ‘big talk’?", 
"When do you choose to make a phone call over sending a text?", 
"How much information is ‘too much information’?", 
"Do you sometimes ‘hide’ behind irony?", 
"How good is your grammar?", 
"Do you speak a second, or third, language?", 
"When do you remember learning a new word?", 
"What does your body language communicate?", 
"Do you like school?", 
"Are you stressed about school?", 
"Are high school students being worked too hard?", 
"What are you really learning at school?", 
"What are you looking forward to, or dreading, this school year?", 
"Would you want to be home-schooled?", 
"Would you like to take a class online?", 
"Would you rather attend a public or a private high school?", 
"How much does it matter to you which high school you attend?", 
"How would you grade your school?", 
"What can other schools learn — and copy — from your school?", 
"What would you miss if you left your school?", 
"Is your school day too short?", 
"What do you hope to get out of high school?", 
"Do you have too much homework?", 
"Does your homework help you learn?", 
"Do you participate in class?", 
"What is your best subject?", 
"What’s the most challenging assignment you’ve ever had?", 
"What memorable experiences have you had in learning science or math?", 
"Are you afraid of math?", 
"Do we need a better way to teach math?", 
"What are the best ways to learn about history?", 
"How would you do on a civics test?", 
"Does your school offer enough opportunities to learn computer programming?", 
"Does your school value students’ digital skills?", 
"Do you know how to code?", 
"Would you like to learn?", 
"What career or technical classes do you wish your school offered?", 
"What was your favorite field trip?", 
"What are your best tips for studying?", 
"Do you use study guides?", 
"Is everything you’ve been taught about study habits wrong?", 
"What would you like to have memorized?", 
"How well do you think standardized tests measure your abilities?", 
"Do your test scores reflect how good your teachers are?", 
"What do you wish your teachers knew about you?", 
"When has a teacher inspired you?", 
"What teacher would you like to thank?", 
"What makes a good teacher?", 
"Have you ever been humiliated by a teacher, and how did it affect you?", 
"Have your teachers or textbooks ever gotten it wrong?", 
"Do your teachers use technology well?", 
"Do you have a tutor?", 
"How do you feel about proms?", 
"Do you want to be ‘promposed’ to?", 
"Is prom worth it?", 
"What role do school clubs and teams play in your life?", 
"How big a problem is bullying or cyberbullying in your school or community?", 
"Would you ever go through hazing to be part of a group?", 
"Is your school a ‘party school’?", 
"Have you been to parties that have gotten out of control?", 
"How common is drug use in your school?", 
"Can students at your school talk openly about their mental health issues?", 
"How does your school deal with students who misbehave?", 
"Do you know people who cheat on high-stakes tests?", 
"How much does your life in school intersect with your life outside school?", 
"Do you ever ‘mix it up’ and socialize with different people at school?", 
"What fads are you and your friends into right now?", 
"Where do you want to go to college?", 
"What are your sources for information about colleges and universities?", 
"What role has community college played in your life or the life of someone you know?", 
"Is college overrated?", 
"How much do you worry about taking the sat or act?", 
"What personal essay topic would you assign to college applicants?", 
"What qualities would you look for in a college roommate?", 
"Would you want to take a gap year after high school?", 
"What makes a graduation ceremony memorable?", 
"What do you want to be when you grow up?", 
"Do you have a life calling?", 
"What’s your dream job?", 
"What are your longtime interests or passions?", 
"Do you think you will have a career that you love?", 
"What do you want more from a career: happiness or wealth?", 
"What investment are you willing to make to get your dream job?", 
"Would you consider a nontraditional occupation?", 
"Would you rather work from home or in an office?", 
"Would you want to be a teacher?", 
"What hidden talents might you have?", 
"What ‘back-to-the-land’ skills do you have or wish you had?", 
"What skill could you teach in two minutes?", 
"What have you made yourself?", 
"Do you have an idea for a business or app?", 
"What would you create if you had funding?", 
"How did you start doing something you love?", 
"Did you ever take a break from doing something you love?", 
"What have you done to earn money?", 
"Do you have a job?", 
"Would you quit if your values did not match your employer’s?", 
"What do you hope to be doing the year after you graduate from college?", 
"Where do you see yourself in ten years?", 
"Do you have a best friend?", 
"How often do you spend one-on-one time with your closest friends?", 
"How do you feel about introducing friends from different parts of your life?", 
"Do you find it easier to make new friends online or in-person?", 
"How good a friend are you?", 
"How have you helped a friend in a time of need?", 
"Do you like your friends?", 
"Is competitiveness an obstacle to making or keeping friendships?", 
"How should you handle the end of a friendship?", 
"Have you ever felt left out?", 
"Have you ever been in love?", 
"What are the most meaningful relationships in your life?", 
"What advice would you give to somebody who just started dating?", 
"Are you allowed to date?", 
"Is dating a thing of the past?", 
"Is hookup culture leaving your generation unhappy and unprepared for love?", 
"What are the basic ‘rules’ for handling breakups?", 
"What’s the best way to get over a breakup?", 
"What are your beliefs about marriage?", 
"What’s the most impressive sports moment you’ve seen?", 
"Who are your sports heroes?", 
"What sports teams do you root for?", 
"Does being a fan help define who you are?", 
"How far would you go to express loyalty to your favorite teams?", 
"Are you a fair-weather fan?", 
"When has a sports team most disappointed you?", 
"Do you watch the super bowl?", 
"What fan memorabilia would you pay big bucks for?", 
"What extreme sports interest you most?", 
"Why do you play sports?", 
"What rules would you like to see changed in your favorite sports?", 
"Do you enjoy playing games or solving puzzles?", 
"What are your favorite board games?", 
"What are your favorite games?", 
"What game would you like to redesign?", 
"Where in the world would you most like to travel?", 
"What is your fantasy vacation?", 
"What would your fantasy road trip be like?", 
"What crazy adventure would you want to take?", 
"What local ‘micro adventures’ would you like to go on?", 
"What’s your perfect family vacation?", 
"How has travel affected you?", 
"What kind of tourist are you?", 
"What are the best souvenirs you’ve ever collected while traveling?", 
"What famous landmarks have you visited?", 
"What’s the coolest thing you’ve ever seen in nature?", 
"How much do you know about the rest of the world?", 
"Would you like to live in another country?", 
"Would you want to be a space tourist?", 
"If you could time-travel, where would you go?", 
"What is your all-time favorite piece of clothing?", 
"Do you have a signature clothing item?", 
"What’s your favorite t-shirt?", 
"Do you care what you wear?", 
"Does what you wear say anything about you as a person?", 
"What does your hairstyle say about you?", 
"What’s on your fashion shopping list?", 
"How far would you go for fashion?", 
"What are the hot fashion trends at your school right now?", 
"What current trends annoy you?", 
"Would you ever consider getting a tattoo?", 
"What are your opinions on cosmetic surgery?", 
"Do photoshopped images make you feel bad about your own looks?", 
"Have you inherited your parents’ attitudes toward their looks?", 
"Has anyone ever said that you look like someone famous?", 
"Do you like to exercise?", 
"Do you get enough exercise?", 
"How has exercise changed your health, your body, or your life?", 
"How much do you think about your weight?", 
"Do you pay attention to calorie counts for food?", 
"Do you pay attention to nutrition labels on food?", 
"How concerned are you about where your food comes from?", 
"Are your eating habits healthy?", 
"Do you eat too quickly?", 
"What are your ‘food rules’?", 
"What are your healthy habits?", 
"What health tips have worked for you?", 
"What rules do you have for staying healthy?", 
"How careful are you in the sun?", 
"What are your sleep habits?", 
"How much of a priority do you make sleep?", 
"Do you get enough sleep?", 
"What are the most memorable meals you’ve ever had?", 
"What’s your favorite holiday food memory?", 
"What’s your comfort food?", 
"What are your favorite junk foods?", 
"What’s your favorite candy?", 
"What’s your favorite sandwich?", 
"Do you prefer your tacos ‘authentic’ or ‘appropriated’?", 
"What food would you like to judge in a taste-off?", 
"Do you cook?", 
"What would you most like to learn to cook or bake?", 
"What messages about food and eating have you learned from your family?", 
"How often does your family eat together?", 
"What are your favorite restaurants?", 
"What restaurant would you most like to review?", 
"What do you eat during the school day?", 
"Do you eat cafeteria food?", 
"Is school lunch really all that bad?", 
"How do you celebrate your birthday?", 
"Will you be wearing a Halloween costume this year?", 
"Do you like scary movies and books?", 
"Do you believe in ghosts?", 
"What are your thanksgiving traditions?", 
"What do you look forward to most – and least – during the holiday season?", 
"What are your tips for enjoying the holiday season?", 
"How will you spend the holiday break?", 
"What does Santa Claus mean to you?", 
"Do you look forward to new year’s eve?", 
"Do you make new year’s resolutions?", 
"How do you fight the winter blues?", 
"What would you do on a snow day?", 
"What are your experiences with severe weather?", 
"How do you feel about valentine’s day?", 
"How do you celebrate spring?", 
"What would your fantasy spring break be like?", 
"What are you looking forward to this summer?", 
"What would your ideal summer camp be like?", 
"What are your favorite summer hangouts?", 
"What’s your favorite summer food?", 
"What is your favorite summer movie?", 
"What’s on your summer reading list?", 
"Do you have a summer job?", 
"Do you choose summer activities to look good on applications?", 
"What are the best things you did this summer?", 
"How do you prepare to go back to school?", 
"How can people make the most of long holiday weekends?", 
"What’s your Sunday routine?", 
"What’s your favorite store?", 
"To what company would you write a letter of complaint or admiration?", 
"To what business would you like to give advice?", 
"Do you ever hang out at the mall?", 
"How would you make over your mall?", 
"Do you shop at locally owned businesses?", 
"What are the best things you’ve acquired secondhand?", 
"How important is it to have a driver’s license?", 
"Are you a good driver?", 
"Do you have a dream car?", 
"Would you like to ride in a car that drives itself?", 
"What are the animals in your life?", 
"What’s your relationship like with your pet?", 
"How well do you know your pet?", 
"What are your thoughts on cats?", 
"Would you want to hang out at a cat cafe?", 
"Why do we love watching animal videos so much?", 
"What are your most memorable stories about wildlife?", 
"How do you feel about zoos?", 
"How green are you?", 
"How do you try to reduce your impact on the environment?", 
"Do you ever feel guilty about what, or how much, you throw away?", 
"How much food does your family waste?", 
"What could you live without?", 
"How do you celebrate earth day?", 
"How would you like to help our world?", 
"What cause would get you into the streets?", 
"Have you ever taken part in a protest?", 
"What would you risk your life for?", 
"When have you spoken out about something you felt had to change?", 
"What would you invent to make the world a better place?", 
"Given unlimited resources, what scientific or medical problem would you investigate?", 
"What organizations do you think people should give to this holiday season?", 
"Do you trust your government?", 
"When you are old enough to vote, will you?", 
"Do you consider yourself a republican, democrat, or independent?", 
"What event in the past do you wish you could have witnessed?", 
"What are the most important changes, in your life and in the world, in the last decade?", 
"What national or international events that you lived through do you remember best?", 
"Why should we care about events in other parts of the world?", 
"What news stories are you following?", 
"How do you get your news?", 
"Is your online world just a ‘filter bubble’ of people with the same opinions?", 
"Do your friends on social media all have the same political opinions you do?", 
"What would you do if you won the lottery?", 
"What superpower do you wish you had?", 
"What era do you wish you had lived in?", 
"Would you want to be a tween or teen star?", 
"Would you want to be a child prodigy?", 
"Would you want to grow up in the public eye?", 
"What kind of robot would you want?", 
"What would you outsource if you could?", 
"What would you like to learn on your own?", 
"What would you be willing to wait in a really long line for?", 
"If you were a super-rich philanthropist, what causes would you support?", 
"What would you do if you were president?", 
"What famous person would you like to visit your school?", 
"Who would be the ideal celebrity neighbor?", 
"What do you want to be doing when you’re eighty?", 
"Do you want to live to one-hundred?", 
"What do you want your obituary to say?"];

